# Generated by Django 4.0.5 on 2023-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldmineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='d_date',
            field=models.DateField(null=True),
        ),
    ]
