# Generated by Django 4.0.5 on 2023-07-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldmineApp', '0003_balance_sheet_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='s_Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goldmineApp.branch'),
        ),
        migrations.AddField(
            model_name='profit_loss',
            name='s_Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goldmineApp.branch'),
        ),
    ]
